-- Run these commands below to create tables inside the postgrest table container

-- Table: public.Users

-- DROP TABLE IF EXISTS public."Users";

CREATE TABLE Users
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Uuid" uuid NOT NULL,
    "FirstName" text COLLATE pg_catalog."default",
    "LastName" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "Password" text COLLATE pg_catalog."default",
    "Roles" text COLLATE pg_catalog."default" NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "IsNewUser" boolean NOT NULL DEFAULT false,
    "Otp" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    "OtpExpiry" timestamp with time zone DEFAULT '-infinity'::date,
    "RegistrationToken" text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    "RefreshToken" text COLLATE pg_catalog."default",
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);




-- Table: public.Images

-- DROP TABLE IF EXISTS public."Images";

CREATE TABLE IF NOT EXISTS public."Images"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FileName" text COLLATE pg_catalog."default",
    "S3Url" text COLLATE pg_catalog."default",
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id")
);


-- this is for testing

-- Table: public.Tests

-- DROP TABLE IF EXISTS public."Tests";

CREATE TABLE IF NOT EXISTS public."Tests"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Username" text COLLATE pg_catalog."default",
    "PasswordHash" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Tests" PRIMARY KEY ("Id")
);
